### ISSUE TITLE
Alexa.service overloads CPU 

### ISSUE THREAD

**Issue by cnoorman** [shivasiddharth/Assistants-Pi#77] opened 2018-10-29 22:11 UTC
I managed to install both Alexa and Google Assistant on my RPI3 with Google AIY hat.
When I start Alexa from command line with: 
`/usr/bin/python -u /home/pi/Assistants-Pi/Alexa/alexa.py` it takes about 8% of the CPU's capacity.
However if I start Alexa through the Alexa.service the CPU load increases to approx. 75% (idle state). Temperature warning starts flashing after few minutes.
Any idea what could cause this difference?

BTW: Google assistant give the same CPU load for both command line and service operation of about 30%.
Thanks.

**Comment by oceank82** [comment] 2018-11-04 18:01
Hey!

I have the same issue with my raspberry(latest model). If I stop the alexa service I have like 35% idle and only google service is up n running. Anyone knows whats going on?

best regards K

**Comment by tony1550** [comment] 2018-11-06 17:13
I'm getting the same problem, once I started the Alexa service my CPU meter raised to about 90%. I'm on a Rpi3b+ with the latest version of Raspian. Both google assistant and Alexa are a bit laggy but it responses to my requests. Also, I noticed that the services restart by themselves I hear the intro chime about every 10 minutes. Any advice is appreciated. thanks

**Comment by shivasiddharth** [comment] 2018-11-06 17:31
I am running the Alexa differently for enabling the audio prompts and indicators, thats the reason for the  high CPU usage. I will try and see if i can bring down the CPU usage.

**Comment by tony1550** [comment] 2018-11-06 17:41
I was tinkering with it a bit and found that disabling the Alexa service and running `python alexa.py` inside the `Assistants-Pi/Alexa/` directory runs the Alexa with CPU usage at normal state around 25-30% for me because I'm also running Magic Mirror but Alexa seems to run a lot better along with Google assistant much better, not sure if this is a fix but its a workaround to keep CPU usage way lower than 95%. The audio and led indicators work fine too

**Comment by HardTYZ** [comment] 2018-11-06 17:56
I found temporary solution, i modify service file, adding `screen -dmS -D` and add `RemainAfterExit=yes`
after restart service CPU usage about 40-60%

 https://unix.stackexchange.com/questions/191621/systemd-service-using-100-of-my-cpu-when-it-doesnt-if-i-start-it-without-syste

my alexa.service file:
```
[Unit]
Description=Companion Service
After=network.target

[Service]
Environment=PATH=/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/screen -dmS -D bash -c '/usr/bin/python -u /home/pi/Assistants-Pi/Alexa/alexa.py'
WorkingDirectory=/home/pi/
StandardOutput=tty,
StandardError=tty
Restart=always
User=pi
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

**Comment by cnoorman** [comment] 2018-11-06 20:41
> I am running the Alexa differently for enabling the audio prompts and indicators, thats the reason for the high CPU usage. I will try and see if i can bring down the CPU usage.

The way you run Alexa works fine as long as you use it standalone. As soon as you run it as a service it starts to eat CPU time. You see that happen in other cases as well, especially when using a `while True` loop in the main program.

**Comment by cnoorman** [comment] 2018-11-06 21:28
I have installed the SampleApp program as a service and this already results in a CPU load of 70%.
Running it from the command line uses about 5% on RPI-3B. So the overloading has nothing to do with alexa.py .

**Comment by liberliutw** [comment] 2018-11-08 08:52
I have the same issue and follow the step to modify service file, install screen package '''sudo apt-get install screen''' adding screen -dmS -D and add RemainAfterExit=yes, now CPU loading down to 20%

**Comment by TedMichalik** [comment] 2018-12-04 15:21
Part of the problem is that there is a stray comma in the alexa.service file:

StandardOutput=tty,

With the debug level set to 9, this is hammering the logs and filling up the SD card with useless messages.

**Comment by shivasiddharth** [comment] 2018-12-04 18:18
@williamhemmingsen , Can you raise a PR ?

**Comment by williamhemmingsen** [comment] 2018-12-04 19:04
done

**Comment by shivasiddharth** [comment] 2018-12-15 21:39
Its now fixed i believe with the last PR.

**Closed by shivasiddharth** 2018-12-15 21:39 UTC

**Comment by harishperla09** [comment] 2019-01-20 18:20
The problem is not solved. Still it is overloading

**Comment by vijayrraut** [comment] 2019-01-26 08:56
Sorry but, I changed the alexa.service as per William's comment, but still the cpu goes to 85%, Please help.
Thanks
