### ISSUE TITLE
in a pickle even after authorizing alexa

### ISSUE THREAD

**Issue by mananhiteshkataria** [shivasiddharth/Assistants-Pi#109] opened 2019-02-13 16:39 UTC
# UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST
# Entering limited interaction mode.

##################################################################

+----------------------------------------------------------------------------+
| In Limited Mode: |
+----------------------------------------------------------------------------+
| Status : Unrecoverable authorization failure. |
+----------------------------------------------------------------------------+
| Info: |
| Press 'i' followed by Enter at any time to see the help screen. |
| Stop an interaction: |
| Press 's' and Enter to stop an ongoing interaction. |
| Privacy mode (microphone off): |
| Press 'm' and Enter to turn on and off the microphone. |
| Speaker Control: |
| Press 'p' followed by Enter at any time to adjust speaker settings. |
| Reset device: |
| Press 'k' followed by Enter at any time to reset your device. This |
| will erase any data stored in the device and you will have to |
| re-register your device. |
| This option will also exit the application. |
| Quit: |
| Press 'q' followed by Enter at any time to quit the application. |
+----------------------------------------------------------------------------+

**Comment by mananhiteshkataria** [comment] 2019-02-13 16:39
this is the mode i am stuck in even after registering device

**Comment by shivasiddharth** [comment] 2019-02-13 18:20
Duplicate of #89

**Closed by shivasiddharth** 2019-02-13 18:20 UTC

**Comment by mananhiteshkataria** [comment] 2019-02-13 18:22
thanks
